version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo-test
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: exemplo!
    ports:
      - "27017:27017"
    volumes:
      - /datav:/data/db     
  mongo-express:
    image: mongo-express
    container_name: mongo-express-test
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://root:exemplo!@mongo-test:27017/"
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: exemplo!
      

